### ISSUE TITLE
Effect of training on RGB

### ISSUE THREAD

**Issue by DavideA** [dariofuoli/RLSP#4]
Hi,
and thank you for sharing your code.

I am trying to reproduce your results. I was wondering whether you observed any differences on PSNR (Y channel) between training on RGB or Y only.

Thanks,
Best,
D

**Comment by dariofuoli** [comment]
Hi,

If you train on RGB, the loss function will treat all color channels equally. The idea to train on the Y channel from YCbCr color space, is to emphasize the loss on the visually more important Y channel (with higher weight on green). The idea is inspired by chroma subsampling, which is used for video compression. Since these losses are different, I would expect some differences also in the evaluation, depending on the metric you calculate.

Best,
Dario
